//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.1.0.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Policy.Application")]
[assembly: AssemblyCompany("Exit Games GmbH")]
[assembly: AssemblyProduct("Photon")]
[assembly: AssemblyCopyright("(c) Exit Games GmbH, http://www.exitgames.com")]

[assembly: ComVisible(false)]
[assembly: Guid("448fcf06-f179-47ed-b3db-ecda4a31207f")]

[assembly: AssemblyVersion("3.2.10.4248")]
[assembly: AssemblyFileVersion("3.2.10.4248")]


